In [1]:
import numpy as np
import pandas as pd
import os
import sys
from itertools import combinations, product
from datetime import datetime
import numpy_indexed as npi
from scipy.stats import mode
from tqdm import tqdm

In [2]:
#pid_ls = np.arange(150).reshape(150,1).astype(np.int32)

pid_ls = []
for i in range(150):
    pid_ls.append(i)

In [2]:
start = datetime.now()
#prod_array = np.array(pid_ls)[np.rollaxis(
#    np.indices((len(pid_ls),) * 5), 0, 5 + 1)
#    .reshape(-1, 5)]

#print(len(prod_array))

print(datetime.now() - start)

0:00:00.000041


In [8]:
def cartesian2(arrays):
    arrays = [np.asarray(a).astype(np.int16) for a in arrays]
    shape = (len(x) for x in arrays)

    ix = np.indices(shape, dtype = np.int16)
    ix = ix.reshape(len(arrays), -1).T

    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]

    return ix

In [9]:
start = datetime.now()

cart_array = cartesian2([pid_ls, pid_ls, pid_ls, pid_ls])
print(len(cart_array))

print(datetime.now() - start)

506250000
0:00:03.627050


In [6]:
start = datetime.now()
cart_array.sort(axis = 1)
print(len(cart_array))
print(datetime.now() - start)

3375000
0:00:00.137049


In [7]:
start = datetime.now()
cart_array = npi.unique(cart_array)
print(len(cart_array))
print(datetime.now() - start)

573800
0:00:02.526249


In [11]:
start = datetime.now()

vals, counts = mode(cart_array, axis = 1)

print(datetime.now() - start)

0:00:03.287214


In [12]:
counts[15789]

array([1])

In [13]:
cart_array[15789]

array([  1,  34, 109])

In [14]:
counted_array = np.hstack((cart_array, counts))

In [15]:
len(counted_array)

573800

In [29]:
counted_array = counted_array[counted_array[:,3] == 1]
len(counted_array)

551300

In [19]:
test = counted_array[:1000]
test[test[:,3] == 1]

array([[  0,   1,   2,   1],
       [  0,   1,   3,   1],
       [  0,   1,   4,   1],
       ..., 
       [  0,   6, 118,   1],
       [  0,   6, 119,   1],
       [  0,   6, 120,   1]])

In [48]:
start = datetime.now()

combo_4 = np.zeros(shape = (1,5))
for pid in pid_ls:
    temp = np.hstack((np.full((len(counted_array), 1), pid), counted_array))
    combo_4 = np.vstack((temp, combo_4))
    
print(datetime.now() - start)

0:00:43.450452


In [49]:
combo_4 = combo_4[:, :4]

In [51]:
start = datetime.now()
combo_4.sort(axis = 1)
print(len(combo_4))
print(datetime.now() - start)
combo_4[:15]

82695001
0:00:01.102648


array([[   0.,    1.,    2.,  149.],
       [   0.,    1.,    3.,  149.],
       [   0.,    1.,    4.,  149.],
       [   0.,    1.,    5.,  149.],
       [   0.,    1.,    6.,  149.],
       [   0.,    1.,    7.,  149.],
       [   0.,    1.,    8.,  149.],
       [   0.,    1.,    9.,  149.],
       [   0.,    1.,   10.,  149.],
       [   0.,    1.,   11.,  149.],
       [   0.,    1.,   12.,  149.],
       [   0.,    1.,   13.,  149.],
       [   0.,    1.,   14.,  149.],
       [   0.,    1.,   15.,  149.],
       [   0.,    1.,   16.,  149.]])

In [52]:
start = datetime.now()
combo_4 = npi.unique(combo_4)
print(len(combo_4))
print(datetime.now() - start)

21914176
0:01:22.529362


In [53]:
start = datetime.now()

vals, counts = mode(combo_4, axis = 1)

print(datetime.now() - start)

0:01:07.237537


In [54]:
counted_array = np.hstack((combo_4, counts))

In [55]:
counted_array = counted_array[counted_array[:,4] == 1]
len(counted_array)

20260275

In [73]:
start = datetime.now()

#test = np.any(np.equal(counted_array, [0,1,2,3,1]).all(1))
test = np.where(np.all(counted_array == [1,2,3,5,1], axis = 1))

print(datetime.now() - start)

0:00:00.417665


In [96]:
start = datetime.now()

combo_5 = np.zeros(shape = (1,6))
for pid in tqdm(pid_ls[:5]):
    temp = np.hstack((np.full((len(counted_array), 1), pid), counted_array[:,:-1]))
    
    temp.sort(axis = 1)
    vals, counts = mode(temp, axis = 1)
    
    temp_array = np.hstack((temp, counts))
    temp_array = temp_array[temp_array[:,5] == 1]
    
    combo_5 = np.vstack((combo_5, temp_array))
    
    temp = []
    temp_array = []
    
print(datetime.now() - start)


100%|██████████| 5/5 [08:10<00:00, 99.29s/it]

0:08:12.769195


In [97]:
print(len(combo_5))
combo_5[:23]

98600006


array([[  0.,   0.,   0.,   0.,   0.,   0.],
       [  0.,   2.,   3.,   4.,   5.,   1.],
       [  0.,   2.,   3.,   4.,   6.,   1.],
       [  0.,   2.,   3.,   4.,   7.,   1.],
       [  0.,   2.,   3.,   4.,   8.,   1.],
       [  0.,   2.,   3.,   4.,   9.,   1.],
       [  0.,   2.,   3.,   4.,  10.,   1.],
       [  0.,   2.,   3.,   4.,  11.,   1.],
       [  0.,   2.,   3.,   4.,  12.,   1.],
       [  0.,   2.,   3.,   4.,  13.,   1.],
       [  0.,   2.,   3.,   4.,  14.,   1.],
       [  0.,   2.,   3.,   4.,  15.,   1.],
       [  0.,   2.,   3.,   4.,  16.,   1.],
       [  0.,   2.,   3.,   4.,  17.,   1.],
       [  0.,   2.,   3.,   4.,  18.,   1.],
       [  0.,   2.,   3.,   4.,  19.,   1.],
       [  0.,   2.,   3.,   4.,  20.,   1.],
       [  0.,   2.,   3.,   4.,  21.,   1.],
       [  0.,   2.,   3.,   4.,  22.,   1.],
       [  0.,   2.,   3.,   4.,  23.,   1.],
       [  0.,   2.,   3.,   4.,  24.,   1.],
       [  0.,   2.,   3.,   4.,  25.,   1.],
       [  

In [5]:
cart_array = []